### PR TITLE
Rewrite in vanilla JS

### PR DESCRIPTION
**Pull request by C-Lodder**
Of course, up to you if you wish to go down this route.

I've added a little extra bit of code so the iframe will now be exactly the same height as the preview image that gets initially loaded.

### CODE REVIEW

**Comment by coolcat-creations** [comment]
Hi @C-Lodder - thank you for your PR, but how can i solve this conflict now? 
Thank you... :)

image

**Comment by C-Lodder** [comment]
Try reinstalling the plugin again. There is no jQuery being used in your plugin now, so not sure why that error is occurring.

**Comment by coolcat-creations** [comment]
It´s reinstalled, i had this error when i used javascript before too and so i decided to make my life easy and use jQuery not to have conflicts ;)

**Comment by C-Lodder** [comment]
What line of the file is the error coming from?

**Comment by coolcat-creations** [comment]
I´m sorry Charlie, it was indeed a cached file... but another issue - the frame is not responsive anymore - i´ll look into this later. Thank you for rewriting the js :)

**Pull request merged**
